### ISSUE TITLE
Settings not saving between different Minecraft sessions

### ISSUE THREAD

**Issue by bendy1234** [ViaVersion/ViaFabricPlus#125]
### General Information

fabric-api-0.83.0+1.20
ViaFabricPlus-2.7.6

### Bug Description

Any settings that are changed will not persist between different Minecraft sessions

### Steps to Reproduce

1. Change any setting in VFP
2. Restart Minecraft
3. Check the setting you changed

### Expected Behavior

The settings I change should not reset

**Comment by bendy1234** [comment]
you'll will see this error in the console:
[17:42:08] [Render thread/INFO]: Stopping!
[17:42:17] [Thread-5/INFO]: [STDERR]: java.io.FileNotFoundException: ViaFabricPlus\settings.json (The system cannot find the path specified)
[17:42:17] [Thread-5/INFO]: [STDERR]: 	at java.base/java.io.FileOutputStream.open0(Native Method)
[17:42:17] [Thread-5/INFO]: [STDERR]: 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
[17:42:17] [Thread-5/INFO]: [STDERR]: 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
[17:42:17] [Thread-5/INFO]: [STDERR]: 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
[17:42:17] [Thread-5/INFO]: [STDERR]: 	at java.base/java.io.FileWriter.<init>(FileWriter.java:96)

**Comment by FlorianMichael** [comment]
What Java version do you have + What operating system + What mods

**Comment by bendy1234** [comment]
> What Java version do you have + What operating system + What mods

Java 17
Windows 10
mods:
fabric-api-0.83.0+1.20
ViaFabricPlus-2.7.6

**Comment by bendy1234** [comment]
It looks like the mod is looking for a folder named `ViaFabricPlus` but the mod is making a folder called `ViaLoader`.
When I copy the "ViaLoader" folder and rename it "ViaFabricPlus", everything works properly

**Comment by FlorianMichael** [comment]
Fixed, thanks!
