### ISSUE TITLE
Can't login BedRock Account(Not Online Mode BedRock)

### ISSUE THREAD

**Issue by zhx201933** [ViaVersion/ViaFabricPlus#169]
### General Information

- architectury 9.0.5
	- cloth-config 11.0.98
	   \-- cloth-basic-math 0.6.1
	- dashloader 5.0.0-beta.1+1.20.0
	   |-- com_github_luben_zstd-jni 1.5.2-2
	   |-- dev_notalpha_taski 2.1.0
	   \-- dev_quantumfusion_hyphen 0.4.0-rc.3
	- dstathud 1.1.0
	- fabric-api 0.83.0+1.20
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-api-lookup-api-v1 1.6.34+4d8536c927
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b27
	   |-- fabric-block-api-v1 1.0.9+e022e5d127
	   |-- fabric-blockrenderlayer-v1 1.1.39+b3afc78b27
	   |-- fabric-client-tags-api-v1 1.0.20+b3afc78b27
	   |-- fabric-command-api-v1 1.2.32+f71b366f27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   |-- fabric-commands-v0 0.2.49+df3654b327
	   |-- fabric-containers-v0 0.1.61+df3654b327
	   |-- fabric-content-registries-v0 4.0.7+b3afc78b27
	   |-- fabric-convention-tags-v1 1.5.3+b3afc78b27
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe27
	   |-- fabric-data-generation-api-v1 12.1.10+b3afc78b27
	   |-- fabric-dimensions-v1 2.1.51+b3afc78b27
	   |-- fabric-entity-events-v1 1.5.21+b3afc78b27
	   |-- fabric-events-interaction-v0 0.6.0+b3afc78b27
	   |-- fabric-events-lifecycle-v0 0.2.61+df3654b327
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a27
	   |-- fabric-item-api-v1 2.1.26+b3afc78b27
	   |-- fabric-item-group-api-v1 4.0.7+b3afc78b27
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da27
	   |-- fabric-keybindings-v0 0.2.34+df3654b327
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-loot-api-v2 1.1.37+b3afc78b27
	   |-- fabric-loot-tables-v1 1.1.41+9e7660c627
	   |-- fabric-message-api-v1 5.1.6+b3afc78b27
	   |-- fabric-mining-level-api-v1 2.1.47+b3afc78b27
	   |-- fabric-models-v0 0.3.35+b3afc78b27
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b27
	   |-- fabric-networking-v0 0.3.48+df3654b327
	   |-- fabric-object-builder-api-v1 11.0.6+b3afc78b27
	   |-- fabric-particles-v1 1.0.28+b3afc78b27
	   |-- fabric-recipe-api-v1 1.0.18+b3afc78b27
	   |-- fabric-registry-sync-v0 2.2.6+b3afc78b27
	   |-- fabric-renderer-api-v1 3.0.1+b3afc78b27
	   |-- fabric-renderer-indigo 1.3.1+b3afc78b27
	   |-- fabric-renderer-registries-v1 3.2.44+df3654b327
	   |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b27
	   |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b27
	   |-- fabric-rendering-v0 1.1.47+df3654b327
	   |-- fabric-rendering-v1 3.0.6+b3afc78b27
	   |-- fabric-resource-conditions-api-v1 2.3.4+b3afc78b27
	   |-- fabric-resource-loader-v0 0.11.7+f7923f6d27
	   |-- fabric-screen-api-v1 2.0.6+b3afc78b27
	   |-- fabric-screen-handler-api-v1 1.3.27+b3afc78b27
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b27
	   |-- fabric-transfer-api-v1 3.2.2+b3afc78b27
	   \-- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b27
	- fabricloader 0.14.21
	- indium 1.0.18+mc1.20
	- java 17
	- litematica 0.14.3
	- magiclib 0.7.336+05361cf-stable
	- malilib 0.15.4
	   \-- fabric-resource-loader-v0 0.11.7+f7923f6d27
	- meteor-client 0.5.4-1857
	   \-- baritone-meteor 1.20.1-SNAPSHOT
	- meteor-rejects 0.3
	   \-- seedcrackerx-api 2.10.1
	- minecraft 1.20
	- notenoughcrashes 4.4.4+1.20
	- roughlyenoughitems 12.0.613
	   \-- error_notifier 1.0.9
	- seedcrackerx 2.14.4
	   |-- com_seedfinding_latticg 1.6
	   |-- com_seedfinding_mc_biome 41a42cb9019a552598f12089059538853e18ec78
	   |-- com_seedfinding_mc_core d64d5f90be66300da41ef58f4f1736db2499784f
	   |-- com_seedfinding_mc_feature 919b7e513cc1e87e029a9cd703fc4e2dc8686229
	   |-- com_seedfinding_mc_math ffd2edcfcc0d18147549c88cc7d8ec6cf21b5b91
	   |-- com_seedfinding_mc_noise 7e3ba65e181796c4a2a1c8881d840b2254b92962
	   |-- com_seedfinding_mc_reversal ca64c0890c106f1a2207623c316fce86f250b918
	   |-- com_seedfinding_mc_seed 1ead6fcefe7e8de4b3d60cd6c4e993f1e8f33409
	   |-- com_seedfinding_mc_terrain b4246cbd5880c4f8745ccb90e1b102bde3448126
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   \-- fabric-resource-loader-v0 0.11.7+f7923f6d27
	- sodium 0.4.10+build.27
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b27
	   |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b27
	   \-- fabric-resource-loader-v0 0.11.7+f7923f6d27
	- sodium-extra 0.4.20+mc1.20-build.103
	   |-- caffeineconfig 1.1.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- starlight 1.1.2+fabric.42e9b6f
	- viafabricplus 2.7.6
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.7
	- xaerominimap 23.4.4
	- xaeroworldmap 1.30.3

### Bug Description

On Mobile Bedrock Edition, we can login to our Microsoft account and play BedRock Minecraft, it is also okay even if we don't have an official Minecraft Account. When I tried to join a Geyser server, it told me i should login to my Xbox Account. When I tried to add my account, it said some error occured, and I can't login my BedRock Account.
*My Minecraft is not online mode*
part of latest.log:
[21:02:08] [ForkJoinPool.commonPool-worker-4/INFO]: [STDERR]: java.util.concurrent.TimeoutException: Failed to get MSA Code. Login timed out
[21:02:08] [ForkJoinPool.commonPool-worker-4/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.msa.StepMsaDeviceCodeMsaCode.applyStep(StepMsaDeviceCodeMsaCode.java:83)
[21:02:08] [ForkJoinPool.commonPool-worker-4/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.msa.StepMsaDeviceCodeMsaCode.applyStep(StepMsaDeviceCodeMsaCode.java:38)
[21:02:08] [ForkJoinPool.commonPool-worker-4/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.AbstractStep.getFromInput(AbstractStep.java:38)
[21:02:08] [ForkJoinPool.commonPool-worker-4/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.AbstractStep.getFromInput(AbstractStep.java:38)
[21:02:08] [ForkJoinPool.commonPool-worker-4/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.OptionalMergeStep.getFromInput(OptionalMergeStep.java:48)
[21:02:08] [ForkJoinPool.commonPool-worker-4/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.OptionalMergeStep.getFromInput(OptionalMergeStep.java:22)
[21:02:08] [ForkJoinPool.commonPool-worker-4/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.AbstractStep.getFromInput(AbstractStep.java:38)
[21:02:08] [ForkJoinPool.commonPool-worker-4/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.AbstractStep.getFromInput(AbstractStep.java:38)
[21:02:08] [ForkJoinPool.commonPool-worker-4/INFO]: [STDERR]: 	at de.florianmichael.viafabricplus.base.settings.groups.AuthenticationSettings.lambda$new$7(AuthenticationSettings.java:52)
[21:02:08] [ForkJoinPool.commonPool-worker-4/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[21:02:08] [ForkJoinPool.commonPool-worker-4/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[21:02:08] [ForkJoinPool.commonPool-worker-4/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[21:02:08] [ForkJoinPool.commonPool-worker-4/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[21:02:08] [ForkJoinPool.commonPool-worker-4/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[21:02:08] [ForkJoinPool.commonPool-worker-4/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[21:02:08] [ForkJoinPool.commonPool-worker-4/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[21:02:08] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: java.util.concurrent.TimeoutException: Failed to get MSA Code. Login timed out
[21:02:08] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.msa.StepMsaDeviceCodeMsaCode.applyStep(StepMsaDeviceCodeMsaCode.java:83)
[21:02:08] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.msa.StepMsaDeviceCodeMsaCode.applyStep(StepMsaDeviceCodeMsaCode.java:38)
[21:02:08] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.AbstractStep.getFromInput(AbstractStep.java:38)
[21:02:08] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.AbstractStep.getFromInput(AbstractStep.java:38)
[21:02:08] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.OptionalMergeStep.getFromInput(OptionalMergeStep.java:48)
[21:02:08] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.OptionalMergeStep.getFromInput(OptionalMergeStep.java:22)
[21:02:08] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.AbstractStep.getFromInput(AbstractStep.java:38)
[21:02:08] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.AbstractStep.getFromInput(AbstractStep.java:38)
[21:02:08] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at de.florianmichael.viafabricplus.base.settings.groups.AuthenticationSettings.lambda$new$7(AuthenticationSettings.java:52)
[21:02:08] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[21:02:08] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[21:02:08] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[21:02:08] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[21:02:08] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[21:02:08] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[21:02:08] [ForkJoinPool.commonPool-worker-5/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[21:02:54] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: java.util.concurrent.TimeoutException: Failed to get MSA Code. Login timed out
[21:02:54] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.msa.StepMsaDeviceCodeMsaCode.applyStep(StepMsaDeviceCodeMsaCode.java:83)
[21:02:54] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.msa.StepMsaDeviceCodeMsaCode.applyStep(StepMsaDeviceCodeMsaCode.java:38)
[21:02:54] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.AbstractStep.getFromInput(AbstractStep.java:38)
[21:02:54] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.AbstractStep.getFromInput(AbstractStep.java:38)
[21:02:54] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.OptionalMergeStep.getFromInput(OptionalMergeStep.java:48)
[21:02:54] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.OptionalMergeStep.getFromInput(OptionalMergeStep.java:22)
[21:02:54] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.AbstractStep.getFromInput(AbstractStep.java:38)
[21:02:54] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.AbstractStep.getFromInput(AbstractStep.java:38)
[21:02:54] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at de.florianmichael.viafabricplus.base.settings.groups.AuthenticationSettings.lambda$new$7(AuthenticationSettings.java:52)
[21:02:54] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[21:02:54] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[21:02:54] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[21:02:54] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[21:02:54] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[21:02:54] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[21:02:54] [ForkJoinPool.commonPool-worker-6/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

### Steps to Reproduce

1. Add BedRock Account
2. Tried to login on my browser
3. Finished login on browser, back to game, it failed

### Expected Behavior

Can login to offline-mode Minecraft Microsoft account.

**Comment by zhx201933** [comment]
i login successful. seems my WLAN glitched lol
