### ISSUE TITLE
Forbidden character NPE crash

### ISSUE THREAD

**Issue by DreenDex** [ViaVersion/ViaFabricPlus#206]
### General Information

Crashes only starting with viafabricplus 2.8.2, version 2.7.8 is unaffected.

Installed mods:

- fabric-api: Fabric API 0.86.1+1.20.1
- viafabricplus: ViaFabricPlus 2.8.2

### Bug Description

```
java.lang.NullPointerException: Cannot invoke "java.util.List.contains(Object)" because the return value of "java.util.Map.get(Object)" is null
	at net.minecraft.class_377.viafabricplus_isForbiddenCharacter(class_377.java:577)
	at net.minecraft.class_377.handler$zlp000$viafabricplus$injectFindGlyph(class_377.java:583)
	at net.minecraft.class_377.method_40038(class_377.java:116)
	at net.minecraft.class_8532.method_51600(class_8532.java:72)
	at net.minecraft.class_377.method_2011(class_377.java:137)
	at net.minecraft.class_327$class_5232.accept(class_327.java:205)
	at net.minecraft.class_5223.method_27477(class_5223.java:17)
	at net.minecraft.class_5223.method_27474(class_5223.java:43)
	at net.minecraft.class_5481.method_30753(class_5481.java:23)
	at net.minecraft.class_5481.method_30743(class_5481.java:82)
	at net.minecraft.class_327.method_27530(class_327.java:298)
	at net.minecraft.class_327.method_1723(class_327.java:151)
	at net.minecraft.class_327.method_22942(class_327.java:84)
	at net.minecraft.class_332.method_51430(class_332.java:288)
	at net.minecraft.class_332.method_51439(class_332.java:298)
	at net.minecraft.class_465.method_2388(class_465.java:195)
	at net.minecraft.class_465.method_25394(class_465.java:129)
	at net.minecraft.class_476.method_25394(class_476.java:28)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

### Steps to Reproduce

1. Join server `mc.aresmine.ru`  with version `1.17.1` so maps are showing content, otherwise replicable on `1.16.5` too.
2. Solve the captcha challenge.
3. Accept the required server resource pack.
4. Just use the compass or NPC in the hub to open a custom menu.
- Client crashes

### Expected Behavior

Containers that have custom characters within its title should open normally, without causing the game crash.

**Comment by FlorianMichael** [comment]
Should be fixed now
