### ISSUE TITLE
Can't log in with Bedrock

### ISSUE THREAD

**Issue by noblereign** [ViaVersion/ViaFabricPlus#227]
### General Information

Minecraft 1.20.1
Only ViaFabricPlus and Fabric-API are installed.
Using Prism Launcher 7.2, if that makes any difference

### Bug Description

Trying to log in with Bedrock fails with an error after inputting the code because a signature doesn't match.

<details>
  <summary>Related logs</summary>
[10:08:32] [ForkJoinPool.commonPool-worker-1/INFO]: Getting device code for MSA login...

[10:08:32] [ForkJoinPool.commonPool-worker-1/INFO]: Got MSA device code, expires: 2023-08-23T10:23:32.468-07:00[America/Los_Angeles]

[10:08:32] [ForkJoinPool.commonPool-worker-1/INFO]: Waiting for MSA login via device code...

[10:09:03] [ForkJoinPool.commonPool-worker-1/INFO]: Got MSA Code

[10:09:03] [ForkJoinPool.commonPool-worker-1/INFO]: Getting MSA Token...

[10:09:03] [ForkJoinPool.commonPool-worker-1/INFO]: Got MSA Token, expires: 2023-08-24T10:09:03.379-07:00[America/Los_Angeles]

[10:09:03] [ForkJoinPool.commonPool-worker-1/INFO]: Authenticating device with Xbox Live...

[10:09:03] [ForkJoinPool.commonPool-worker-1/INFO]: Got XBL Device Token, expires: 2023-09-06T10:09:03.764-07:00[America/Los_Angeles]

[10:09:03] [ForkJoinPool.commonPool-worker-1/INFO]: Authenticating with Xbox Live using SISU...

[10:09:04] [ForkJoinPool.commonPool-worker-1/INFO]: Got XBL Title+User+XSTS Token, expires: 2023-08-23T14:09:04.074-07:00[America/Los_Angeles]

[10:09:04] [ForkJoinPool.commonPool-worker-1/INFO]: Authenticating with Minecraft Services...

[10:09:04] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: io.jsonwebtoken.security.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.

[10:09:04] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:399)

[10:09:04] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:529)

[10:09:04] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:589)

[10:09:04] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at io.jsonwebtoken.impl.ImmutableJwtParser.parseClaimsJws(ImmutableJwtParser.java:173)

[10:09:04] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.bedrock.StepMCChain.applyStep(StepMCChain.java:89)

[10:09:04] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.bedrock.StepMCChain.applyStep(StepMCChain.java:48)

[10:09:04] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.AbstractStep.getFromInput(AbstractStep.java:38)

[10:09:04] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at de.florianmichael.viafabricplus.base.settings.groups.BedrockSettings.lambda$new$8(BedrockSettings.java:51)

[10:09:04] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at 
java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)

[10:09:04] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)

[10:09:04] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)

[10:09:04] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)

[10:09:04] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)

[10:09:04] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)

[10:09:04] [ForkJoinPool.commonPool-worker-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
</details>

### Steps to Reproduce

1. Go to settings and initiate Bedrock linking
2. Copy the code, enter it, proceed as normal
3. When it tells you you're ready to go, the Minecraft window will say something went wrong.
4. (bonus) you can't exit the error screen and have to close your game lol

### Expected Behavior

I should be logged into Bedrock after it tells me i'm good to go

Video of the issue:
https://github.com/ViaVersion/ViaFabricPlus/assets/2935979/a1feafa9-73aa-4393-a6e0-b086c5202efc

**Comment by RaphiMC** [comment]
Can you try if the bedrock login works on ViaProxy

**Comment by RaphiMC** [comment]
Fixed the issue in MinecraftAuth and ViaBedrock (You will have to wait for a new ViaFabricPlus release or use ViaBedrock directly)
