### ISSUE TITLE
Unable to connect to Minecraft Bedrock Edition account.

### ISSUE THREAD

**Issue by INV-PLA** [ViaVersion/ViaFabricPlus#243]
### General Information

"XaerosWorldMap_1.34.1_Fabric_1.20.jar"
"yet-another-config-lib-fabric-3.1.1+1.20.jar"
"zmusic-fabric-1.20-3.2.0.jar"
"[投影打印机_宅闲鱼二改版]litematica-printer-1.20.1-20230628-2.4.jar"
"appleskin-fabric-mc1.20-2.5.0.jar"
"baritone-api-fabric-1.10.1.jar"
"BetterPingDisplay-Fabric-1.20.1-1.1.1.jar"
"c2me-fabric-mc1.20.1-0.2.0+alpha.10.106.jar"
"chesttracker-1.20.1-1.1.22.jar"
"clientcommands-2.8.3.jar"
"cloth-config-11.1.106-fabric.jar"
"cloudmusic-mod-1.20.x-0.4.5.jar"
"cmdkeybind-1.6.3-1.20.jar"
"command-block-ide-0.4.4.jar"
"cr-arrows-info-fabric-1.2.3+1.20.jar"
"dashloader-5.0.0-beta.2+1.20.0.jar"
"disc_jockey-1.2.5.jar"
"do-a-barrel-roll-3.3.2+1.20-fabric.jar"
"emi_loot-0.6.5+1.20.1.jar"
"emi-1.0.19+1.20.1+fabric.jar"
"emitrades-fabric-1.2.0+mc1.20.1.jar"
"entity_model_features_fabric_1.20-0.RC.4.jar"
"entity_texture_features_fabric_1.20-4.5.1.jar"
"fabric-api-0.88.1+1.20.1.jar"
"fabric-carpet-1.20-1.4.112+v230608.jar"
"fabric-language-kotlin-1.10.10+kotlin.1.9.10.jar"
"Fastload-Reforged-mc1.20.1-3.4.0.jar"
"Female-Gender-Mod-fabric-1.20-3.0.1.jar"
"forcecloseloadingscreen-2.1.1.jar"
"FpsReducer2-fabric-1.20-2.5.jar"
"horse-stats-vanilla-4.3.0.jar"
"I18nUpdateMod-3.5.0-all.jar"
"IBEEditor-1.20-2.2.3-fabric.jar"
"Identifier-Translation-3_1.20-1.20.1.jar"
"idwtialsimmoedm-0.2.0+1.20.jar"
"InGameAccountSwitcher-Fabric-1.20-8.0.2.jar"
"InventoryProfilesNext-fabric-1.20-1.10.7.jar"
"iris-mc1.20.1-1.6.7.jar"
"itemscroller-fabric-1.20.1-0.20.0.jar"
"libIPN-fabric-1.20-4.0.0.jar"
"librarian-trade-finder-2.0.1.jar"
"litematica-fabric-1.20.1-0.15.3.jar"
"lithium-fabric-mc1.20.1-0.11.2.jar"
"magiclib-all-0.7.364+85d9866-stable.jar"
"malilib-fabric-1.20.1-0.16.2.jar"
"MasaGadget-all-3.2.318+67ab5b4-stable.jar"
"minihud-fabric-1.20.1-0.27.0.jar"
"modelfix-1.14-fabric.jar"
"modernfix-fabric-5.7.2+mc1.20.1.jar"
"modmenu-7.0.1.jar"
"moreculling-1.20.1-0.19.0.jar"
"my-beloved-icon-1.0-SNAPSHOT.jar"
"NBTac-FABRIC-1.20.1-1.1.6.jar"
"NoChatReports-FABRIC-1.20.1-v2.2.2.jar"
"Pick-Block-Pro-1.7.20-mc1.20.1.jar"
"polymer-bundled-0.5.15+1.20.1.jar"
"redirectionor-1.20.1-4.3.2-fabric.jar"
"reeses_sodium_options-1.6.5+mc1.20.1-build.95.jar"
"serverpingerfixer-1.0.1.jar"
"sodium-extra-0.5.1+mc1.20.1-build.112.jar"
"sodium-fabric-mc1.20.1-0.5.1.jar"
"spu-1.6.jar"
"spyglass_astronomy-1.0.5-mc1.20+.jar"
"starlight-1.1.2+fabric.dbc156f.jar"
"status-effect-bars-1.0.3.jar"
"stendhal-1.3.9-1.20.jar"
"TES-fabric-1.20.1-1.3.jar"
"tooltipfix-1.1.1-1.20.jar"
"tweakermore-mc1.20.1-v3.14.0.jar"
"tweakeroo-fabric-1.20.1-0.17.1.jar"
"viafabricplus-2.8.5.jar"
"WorldEditCUI-1.20+01.jar"
"Xaeros_Minimap_23.8.0_Fabric_1.20.jar"

### Bug Description

Add Bedrock Edition, after confirming in the browser, an error occurs, and clicking cancel cannot exit.
[21:34:14] [ForkJoinPool.commonPool-worker-96/INFO]: Getting device code for MSA login...
[21:34:16] [ForkJoinPool.commonPool-worker-96/INFO]: Got MSA device code, expires: 2023-09-14T21:49:16.014+08:00[Asia/Shanghai]
[21:34:16] [ForkJoinPool.commonPool-worker-96/INFO]: Waiting for MSA login via device code...
[21:34:21] [ForkJoinPool.commonPool-worker-98/INFO]: Getting device code for MSA login...
[21:34:22] [ForkJoinPool.commonPool-worker-98/INFO]: Got MSA device code, expires: 2023-09-14T21:49:22.309+08:00[Asia/Shanghai]
[21:34:22] [ForkJoinPool.commonPool-worker-98/INFO]: Waiting for MSA login via device code...
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: Got MSA Code
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: Getting MSA Token...
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: org.apache.http.client.HttpResponseException: status code: 500, reason phrase: Internal Server Error
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.msa.MsaResponseHandler.handleResponse(MsaResponseHandler.java:46)
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.msa.MsaResponseHandler.handleResponse(MsaResponseHandler.java:32)
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.msa.StepMsaToken.apply(StepMsaToken.java:89)
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.msa.StepMsaToken.applyStep(StepMsaToken.java:47)
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.msa.StepMsaToken.applyStep(StepMsaToken.java:37)
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.AbstractStep.getFromInput(AbstractStep.java:38)
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.OptionalMergeStep.getFromInput(OptionalMergeStep.java:48)
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.OptionalMergeStep.getFromInput(OptionalMergeStep.java:22)
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.AbstractStep.getFromInput(AbstractStep.java:38)
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at net.raphimc.mcauth.step.AbstractStep.getFromInput(AbstractStep.java:38)
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at de.florianmichael.viafabricplus.base.settings.groups.BedrockSettings.lambda$new$8(BedrockSettings.java:47)
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[21:34:33] [ForkJoinPool.commonPool-worker-98/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

### Steps to Reproduce

Open the game.
Click on multiplayer.
Open ViaFabricPlus.
Open settings.
Click on "Click here to connect to your Bedrock Edition account."
Copy the code.
Paste the code on the browser page and click next.
Log in to your account on the browser.
If an error page appears and you are unable to exit, try cancelling.

### Expected Behavior

Even if an error occurs, clicking cancel should at least allow you to exit the error page.

**Comment by RaphiMC** [comment]
The error looks like a temporary error from microsoft or maybe a rate limit. Can you try it again and see if it still fails

**Comment by Omena0** [comment]
For me downloading the latest snapshot of authlib manually worked, try that.

**Comment by INV-PLA** [comment]
> I'm closing the issue now because I can't reproduce it and it's probably as RK says only a temporary error, if the error still occurs after further attempts (with waiting time), feel free to reopen the issue.

Is it possible that it has something to do with win 7 in China?

**Comment by HowardZHY** [comment]
> > I'm closing the issue now because I can't reproduce it and it's probably as RK says only a temporary error, if the error still occurs after further attempts (with waiting time), feel free to reopen the issue.
> 
> Is it possible that it has something to do with win 7 in China?

Unlikly.

除非你的运营商阻止了部分微软服务或与微软服务联通不畅，请自行搜寻如何更改DNS。
