### ISSUE TITLE
Failed to join a 1.20.1 server with ViaFabricPlus 2.9.3 on 1.20.2: Invalid payload REGISTER

### ISSUE THREAD

**Issue by eternitymoe** [ViaVersion/ViaFabricPlus#253]
### General Information

Client mod list:
```
Fabric Mods: 
		fabric-api: Fabric API 0.89.2+1.20.2
			fabric-api-base: Fabric API Base 0.4.32+fce67b32a0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.40+fce67b32a0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.11+86b12645a0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.42+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.3+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.35+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.14+86b12645a0
			fabric-commands-v0: Fabric Commands (v0) 0.2.52+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.71+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.3+0ba8e9cea0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.6+f4b7e424a0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.1+bbae80faa0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.55+b1229956a0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.24+f4b7e424a0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.8+daef22a2a0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.67+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+f4b7e424a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.31+43511215a0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+f4b7e424a0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b3a0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.25+3bafade3a0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.0.1+0ba8e9cea0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.0+fce67b32a0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.53+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.4+f4b7e424a0
			fabric-models-v0: Fabric Models (v0) 0.4.3+9386d8a7a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.0.7+74a33ae7a0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.0+b1b4f7b0a0
			fabric-particles-v1: Fabric Particles (v1) 1.1.3+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.4+43511215a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.2+34a3e0e2a0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.47+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.38+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.29+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.50+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.9+86b12645a0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+43511215a0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+86b12645a0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.10+0ba8e9cea0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.37+86b12645a0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.7+109a65e5a0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.2+fce67b32a0
		fabricloader: Fabric Loader 0.14.22
		iris: Iris 1.6.9
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.2
		modmenu: Mod Menu 8.0.0-beta.2
		sodium: Sodium 0.5.3
		viafabricplus: ViaFabricPlus 2.9.3
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.9
```

### Bug Description

Failed to using ViaFabricPlus 2.9.3 on Fabric 1.20.2 to join a 1.20.1 server.
Client disconnected because of error at server side (caused by packet translation?)
The server side log is listed below:
```
[13:35:47 INFO]: UUID of player <PLAYERNAME> is <PLAYERUUID>
[13:35:47 INFO]: <PLAYERNAME>[/<IPADDRESS>] logged in with entity id 8687 at ([world]<X>, <Y>, <Z>)
[13:35:48 ERROR]: Couldn't register custom payload
org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 64 chars (attempted 73 - '<UUID>:<UUID>.
        at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:500) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.addChannel(CraftPlayer.java:2339) ~[paper-1.20.1.jar:git-Paper-161]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomPayload(ServerGamePacketListenerImpl.java:3604) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-161]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-161]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-161]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-161]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-161]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-161]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-161]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-161]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:35:48 INFO]: <PLAYERNAME> lost connection: Invalid payload REGISTER!

```

### Steps to Reproduce

1. use a 1.20.2 client with ViaFabricPlus 2.9.3
2. join a 1.20.1 server
3. failed to join server

### Expected Behavior

join the server with no error

**Comment by JuliGame** [comment]
Same error here

**Comment by Pan4ur** [comment]
Same

**Comment by dylanmilesmsu** [comment]
Happens to me even when connecting to a 1.20.2 server with a 1.20.2 client

**Comment by FlorianMichael** [comment]
The fix will be published within the next version
