### ISSUE TITLE
Crash when with "No Chat Reports" mod

### ISSUE THREAD

**Issue by bluegreensea** [ViaVersion/ViaFabricPlus#255]
### General Information

ViaFabricPlus, Fabric-API, No Chat Reports

```
java.lang.RuntimeException: Unexpected ReflectiveOperationException occurred (Gson 2.10.1). To support Java records, reflection is utilized to read out information about records. All these invocations happens after it is established that records exist in the JVM. This exception is unexpected behavior.
	at com.google.gson.internal.reflect.ReflectionHelper.createExceptionForRecordReflectionException(ReflectionHelper.java:162)
	at com.google.gson.internal.reflect.ReflectionHelper.access$300(ReflectionHelper.java:10)
	at com.google.gson.internal.reflect.ReflectionHelper$RecordSupportedHelper.getAccessor(ReflectionHelper.java:244)
	at com.google.gson.internal.reflect.ReflectionHelper.getAccessor(ReflectionHelper.java:144)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:266)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:125)
	at com.google.gson.Gson.getAdapter(Gson.java:556)
	at com.google.gson.Gson.fromJson(Gson.java:1226)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1047)
	at com.google.gson.Gson.fromJson(Gson.java:982)
	at com.mojang.authlib.minecraft.client.ObjectMapper.readValue(ObjectMapper.java:30)
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:93)
	at com.mojang.authlib.minecraft.client.MinecraftClient.post(MinecraftClient.java:65)
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.getKeyPair(YggdrasilUserApiService.java:71)
	at net.minecraft.class_7434.method_43605(class_7434.java:130)
	at net.minecraft.class_7434.method_44291(class_7434.java:79)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NoSuchMethodException: com.mojang.authlib.yggdrasil.response.KeyPairResponse.viafabricplus_legacyKeySignature()
	at java.base/java.lang.Class.getMethod(Class.java:2227)
	at com.google.gson.internal.reflect.ReflectionHelper$RecordSupportedHelper.getAccessor(ReflectionHelper.java:242)
	... 21 more
```

### Bug Description

Crash on startup
[crash-2023-09-28_16.49.55-client.txt](https://github.com/ViaVersion/ViaFabricPlus/files/12747561/crash-2023-09-28_16.49.55-client.txt)
[latest.log](https://github.com/ViaVersion/ViaFabricPlus/files/12747582/latest.log)

### Steps to Reproduce

1. Start game
2. Game crashes

### Expected Behavior

not crash

**Comment by FlorianMichael** [comment]
Please report this issue to NoChatReports https://github.com/Aizistral-Studios/No-Chat-Reports/issues

**Comment by FlorianMichael** [comment]
Fixed in https://github.com/ViaVersion/ViaFabricPlus/commit/f88407f0bd38a43c24eb4d71a772bc1bddd70da7
