### ISSUE TITLE
Make a new 1.20.1 release Please

### ISSUE THREAD

**Issue by HowardZHY** [ViaVersion/ViaFabricPlus#267]
### General Information

Please make a new 1.20.1 release with Via* updated.

### Bug Description

[15:02:28] [main/INFO]: Loaded overriding jar ViaBackwards-4.9.0-23w41a-SNAPSHOT.jar
[15:02:29] [main/INFO]: Loaded overriding jar ViaVersion-4.9.0-23w41a-SNAPSHOT.jar
[15:02:29] [main/WARN]: No Bedrock account could be found
[15:02:29] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: 'void com.viaversion.viaversion.configuration.AbstractViaConfig.reloadConfig()'
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'void com.viaversion.viaversion.configuration.AbstractViaConfig.reloadConfig()'
	at de.florianmichael.viafabricplus.protocolhack.impl.platform.ViaFabricPlusViaVersionPlatformImpl.createConfig(ViaFabricPlusViaVersionPlatformImpl.java:35) ~[viafabricplus-2.8.7.jar:?]
	at net.raphimc.vialoader.impl.platform.ViaVersionPlatformImpl.<init>(ViaVersionPlatformImpl.java:52) ~[viafabricplus-2.8.7.jar:?]
	at de.florianmichael.viafabricplus.protocolhack.impl.platform.ViaFabricPlusViaVersionPlatformImpl.<init>(ViaFabricPlusViaVersionPlatformImpl.java:29) ~[viafabricplus-2.8.7.jar:?]
	at de.florianmichael.viafabricplus.protocolhack.ProtocolHack.init(ProtocolHack.java:214) ~[viafabricplus-2.8.7.jar:?]
	at de.florianmichael.viafabricplus.ViaFabricPlus.init(ViaFabricPlus.java:90) ~[viafabricplus-2.8.7.jar:?]
	at net.minecraft.client.main.Main.handler$dkp000$viafabricplus$preLoad(Main.java:1032) ~[1.20.1-Fabric.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:164) ~[1.20.1-Fabric.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	... 8 more

### Steps to Reproduce

Use latest Via* jar from Modrinth to override.
Crash on launch.

### Expected Behavior

Game successfully launched

**Comment by Kichura** [comment]
Since 1.20.2 essentially superseded 1.20.1, it will not be considered.

**Comment by HowardZHY** [comment]
> Since 1.20.2 essentially superseded 1.20.1, it will not be considered.

No, there're still many mods/modpacks that haven't updated to 1.20.2, so it's needed for many players.

**Comment by FlorianMichael** [comment]
@HowardZHY It doesn't change the fact that I'm not maintaing older versions of ViaFabricPlus, the last ViaVersion commits broke internal API and I don't want to randomly make releases for older versions, they were never actively maintained by me and this won't change. You can always use the ViaProxy, since ViaFabricPlus doesn't provide backwards QoL Fixes anyways.

**Comment by HowardZHY** [comment]
> @HowardZHY It doesn't change the fact that I'm not maintaing older versions of ViaFabricPlus, the last ViaVersion commits broke internal API and I don't want to randomly make releases for older versions, they were never actively maintained by me and this won't change. You can always use the ViaProxy, since ViaFabricPlus doesn't provide backwards QoL Fixes anyways.

Would you accept 1.20.1 PRs? I believe there'll be more than 5000 downloads if there's a new 1.20.1 release

**Comment by FlorianMichael** [comment]
If someone wants to maintain ViaFabricPlus for 1.20.1 and/or 1.19.4 further, he can make pull requests to the old branches, and they will be merged. Depending on that, if someone does that I can note in the modrinth description that there are such ports, but I will not make official Modrinth/GitHub releases for these builds.

**Comment by FlorianMichael** [comment]
Published at modrinth: https://modrinth.com/mod/viafabricplus/version/0.0.1
