### ISSUE TITLE
incompatibility with interactic

### ISSUE THREAD

**Issue by Miloxium** [ViaVersion/ViaFabricPlus#375]
### General Information

[10/03/2024 19:34:26 PM] [Render thread/WARN] @Redirect conflict. Skipping viafabricplus.mixins.json:fixes.minecraft.MixinMinecraftClient from mod viafabricplus->@Redirect::disableSwing(Lnet/minecraft/class_746;Lnet/minecraft/class_1268;)V with priority 1000, already redirected by interactic.mixins.json:MinecraftClientMixin from mod interactic->@Redirect::dontSwingArms(Lnet/minecraft/class_746;Lnet/minecraft/class_1268;)V with priority 1000
[10/03/2024 19:34:26 PM] [Render thread/WARN] @Redirect conflict. Skipping viafabricplus.mixins.json:fixes.minecraft.MixinMinecraftClient from mod viafabricplus->@Redirect::disableSwing(Lnet/minecraft/class_746;Lnet/minecraft/class_1268;)V with priority 1000, already redirected by interactic.mixins.json:MinecraftClientMixin from mod interactic->@Redirect::dontSwingArms(Lnet/minecraft/class_746;Lnet/minecraft/class_1268;)V with priority 1000
[10/03/2024 19:34:26 PM] 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
[10/03/2024 19:34:26 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472)
[10/03/2024 19:34:26 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[10/03/2024 19:34:26 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[10/03/2024 19:34:26 PM] Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
[10/03/2024 19:34:26 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
[10/03/2024 19:34:26 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
[10/03/2024 19:34:26 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
[10/03/2024 19:34:26 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
[10/03/2024 19:34:26 PM] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[10/03/2024 19:34:26 PM] 	at net.minecraft.client.main.Main.main(Main.java:233)
[10/03/2024 19:34:26 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[10/03/2024 19:34:26 PM] 	... 2 more
[10/03/2024 19:34:26 PM] Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[10/03/2024 19:34:26 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[10/03/2024 19:34:26 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
[10/03/2024 19:34:26 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
[10/03/2024 19:34:26 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
[10/03/2024 19:34:26 PM] 	... 8 more
[10/03/2024 19:34:26 PM] Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector disableSwing(Lnet/minecraft/class_746;Lnet/minecraft/class_1268;)V in viafabricplus.mixins.json:fixes.minecraft.MixinMinecraftClient from mod viafabricplus failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap viafabricplus-refmap.json
[10/03/2024 19:34:26 PM] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
[10/03/2024 19:34:26 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
[10/03/2024 19:34:26 PM] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
[10/03/2024 19:34:26 PM] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
[10/03/2024 19:34:26 PM] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
[10/03/2024 19:34:26 PM] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
[10/03/2024 19:34:26 PM] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
[10/03/2024 19:34:26 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[10/03/2024 19:34:26 PM] 	... 11 more
[10/03/2024 19:34:26 PM] [Render thread/ERROR] Minecraft has crashed!

### Bug Description

just dont start with interactic.

### Steps to Reproduce

create instance, install interactic and viafabricplus, start and watch.

### Expected Behavior

dont start.

**Comment by FlorianMichael** [comment]
Which Minecraft version are you using?

**Comment by Miloxium** [comment]
1.20.4

**Comment by FlorianMichael** [comment]
Thanks for reporting this issue!
It should already be fixed in https://github.com/ViaVersion/ViaFabricPlus/actions/runs/8215224548 with some internal rewrite we did.
Have a great day
