### ISSUE TITLE
[1.20.6→1.12.2] Decoding error when connecting to any 1.12.2 server

### ISSUE THREAD

**Issue by Felix14-v2** [ViaVersion/ViaFabricPlus#425]
### General Information

[latest.log](https://github.com/user-attachments/files/15520476/latest.log)
<details>
 <summary>Error message</summary>

```
[08:01:50] [Render thread/INFO]: Connecting to localhost, 25565
[08:01:52] [Netty Client IO #3/WARN]: ERROR IN Protocol1_20_3To1_20_5 IN REMAP OF UPDATE_RECIPES (0x73)
[08:01:52] [Netty Client IO #3/WARN]: ERROR IN Protocol1_12_2To1_13 IN REMAP OF RECIPE (0x31)
[08:01:52] [Netty Client IO #3/ERROR]: Error occurred while decoding packet in ViaDecoder
io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.protocols.v1_20_3to1_20_5.rewriter.BlockItemPacketRewriter1_20_5$$Lambda/0x0000018454da54f8, Source 1: com.viaversion.viaversion.protocols.v1_12_2to1_13.Protocol1_12_2To1_13$6 (Anonymous)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[netty-codec-4.1.97.Final.jar:?]
	at net.raphimc.vialoader.netty.ViaDecoder.channelRead(ViaDecoder.java:56) ~[net_raphimc_vialoader-3.0.0-SNAPSHOT-93b195034ffd73fd.jar:?]
	at de.florianmichael.viafabricplus.protocoltranslator.netty.ViaFabricPlusViaDecoder.channelRead(ViaFabricPlusViaDecoder.java:45) ~[ViaFabricPlus-3.3.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202) ~[netty-handler-4.1.97.Final.jar:?]
	at io.netty.handler.flow.FlowControlHandler.read(FlowControlHandler.java:139) ~[netty-handler-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:837) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:814) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.flow.FlowControlHandler.read(FlowControlHandler.java:146) ~[netty-handler-4.1.97.Final.jar:?]
	at de.florianmichael.viafabricplus.protocoltranslator.netty.NoReadFlowControlHandler.read(NoReadFlowControlHandler.java:30) ~[ViaFabricPlus-3.3.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:837) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.access$2000(AbstractChannelHandlerContext.java:61) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext$Tasks$2.run(AbstractChannelHandlerContext.java:1288) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.protocols.v1_20_3to1_20_5.rewriter.BlockItemPacketRewriter1_20_5$$Lambda/0x0000018454da54f8, Source 1: com.viaversion.viaversion.protocols.v1_12_2to1_13.Protocol1_12_2To1_13$6 (Anonymous)
Caused by: java.lang.ArrayStoreException: com.viaversion.viaversion.api.minecraft.item.StructuredItem
	at com.viaversion.viaversion.rewriter.RecipeRewriter.handleIngredient(RecipeRewriter.java:165) ~[com_viaversion_viaversion-common6.110413-20-ed81ee11f32fa2a6.jar:?]
	at com.viaversion.viaversion.rewriter.RecipeRewriter.handleIngredients(RecipeRewriter.java:172) ~[com_viaversion_viaversion-common6.110413-20-ed81ee11f32fa2a6.jar:?]
	at com.viaversion.viaversion.protocols.v1_19_1to1_19_3.rewriter.RecipeRewriter1_19_3.handleCraftingShapeless(RecipeRewriter1_19_3.java:52) ~[com_viaversion_viaversion-common6.110413-20-ed81ee11f32fa2a6.jar:?]
	at com.viaversion.viaversion.rewriter.RecipeRewriter.handleRecipeType(RecipeRewriter.java:61) ~[com_viaversion_viaversion-common6.110413-20-ed81ee11f32fa2a6.jar:?]
	at com.viaversion.viaversion.protocols.v1_20_3to1_20_5.rewriter.BlockItemPacketRewriter1_20_5.lambda$registerPackets$7(BlockItemPacketRewriter1_20_5.java:342) ~[com_viaversion_viaversion-common6.110413-20-ed81ee11f32fa2a6.jar:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:405) ~[com_viaversion_viaversion-common6.110413-20-ed81ee11f32fa2a6.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:369) ~[com_viaversion_viaversion-common6.110413-20-ed81ee11f32fa2a6.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.constructPacket(PacketWrapperImpl.java:300) ~[com_viaversion_viaversion-common6.110413-20-ed81ee11f32fa2a6.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.sendNow(PacketWrapperImpl.java:276) ~[com_viaversion_viaversion-common6.110413-20-ed81ee11f32fa2a6.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.send0(PacketWrapperImpl.java:268) ~[com_viaversion_viaversion-common6.110413-20-ed81ee11f32fa2a6.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.send(PacketWrapperImpl.java:253) ~[com_viaversion_viaversion-common6.110413-20-ed81ee11f32fa2a6.jar:?]
	at com.viaversion.viaversion.api.protocol.packet.PacketWrapper.send(PacketWrapper.java:180) ~[com_viaversion_viaversion-common6.110413-20-ed81ee11f32fa2a6.jar:?]
	at com.viaversion.viaversion.protocols.v1_12_2to1_13.Protocol1_12_2To1_13$6.lambda$register$2(Protocol1_12_2To1_13.java:399) ~[com_viaversion_viaversion-common6.110413-20-ed81ee11f32fa2a6.jar:?]
	at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:179) ~[com_viaversion_viaversion-common6.110413-20-ed81ee11f32fa2a6.jar:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:405) ~[com_viaversion_viaversion-common6.110413-20-ed81ee11f32fa2a6.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:369) ~[com_viaversion_viaversion-common6.110413-20-ed81ee11f32fa2a6.jar:?]
	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122) ~[com_viaversion_viaversion-common6.110413-20-ed81ee11f32fa2a6.jar:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:337) ~[com_viaversion_viaversion-common6.110413-20-ed81ee11f32fa2a6.jar:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:313) ~[com_viaversion_viaversion-common6.110413-20-ed81ee11f32fa2a6.jar:?]
	at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:246) ~[com_viaversion_viaversion-common6.110413-20-ed81ee11f32fa2a6.jar:?]
	at net.raphimc.vialoader.netty.ViaDecoder.decode(ViaDecoder.java:45) ~[net_raphimc_vialoader-3.0.0-SNAPSHOT-93b195034ffd73fd.jar:?]
	at net.raphimc.vialoader.netty.ViaDecoder.decode(ViaDecoder.java:30) ~[net_raphimc_vialoader-3.0.0-SNAPSHOT-93b195034ffd73fd.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[netty-codec-4.1.97.Final.jar:?]
	... 21 more
[08:01:52] [Netty Client IO #3/INFO]: [CHAT] [ViaFabricPlus] An error occurred while translating a packet! See more details in the logs!
```
</details>

### Bug Description

https://github.com/ViaVersion/ViaFabricPlus/assets/75726196/639c469a-0e24-4d6e-96d9-fae2f9b6a915

### Steps to Reproduce

1. Join a 1.12.2 server
2. See the error

### Info
- Minecraft 1.20.6
- Fabric Loader 0.15.11
- Fabric API 0.99.0
- ViaFabricPlus 3.3.0

**Comment by Felix14-v2** [comment]
Oh, seems to be fixed in the latest dev version
[latest.log](https://github.com/user-attachments/files/15520488/latest.log)
