### ISSUE TITLE
Clients without the mod can't join when opening to LAN

### ISSUE THREAD

**Issue by YoshiRulz** [ViaVersion/ViaFabricPlus#430]
### General Information

Host instance (MC 1.20.4 with ViaFabricPlus 3.1.1 installed) is fine. Similar problem if the host installs the "1.20.4 Backport" alpha instead.

<details>
<summary>relevant part of client instance's log</summary>

```
[17:13:44] [Render thread/ERROR]: Received unknown remote registry entries from server
[17:13:44] [Render thread/ERROR]: Registry entry (viafabricplus:footstep) is missing from local registry (minecraft:particle_type)
[17:13:44] [Render thread/ERROR]: Registry remapping failed!
java.util.concurrent.CompletionException: net.fabricmc.fabric.impl.registry.sync.RemapException: Received a registry entry that is unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

viafabricplus

	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:146) ~[fabric-registry-sync-v0-4.0.18+78d798af4f-4d8236a4789003c6.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: net.fabricmc.fabric.impl.registry.sync.RemapException: Received a registry entry that is unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

viafabricplus

	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.checkRemoteRemap(RegistrySyncManager.java:365) ~[fabric-registry-sync-v0-4.0.18+78d798af4f-4d8236a4789003c6.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:261) ~[fabric-registry-sync-v0-4.0.18+78d798af4f-4d8236a4789003c6.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:143) ~[fabric-registry-sync-v0-4.0.18+78d798af4f-4d8236a4789003c6.jar:?]
	... 14 more
[17:13:44] [Render thread/WARN]: Client disconnected with reason: Received a registry entry that is unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

viafabricplus
```
</details>

I thought this might be related to #310, so I tried installing version 3.0.2 on the host, and while the client wasn't able to connect it was with a different error message.

### Bug Description

Vanilla clients can join fine; only clients *with Fabric API but without ViaFabricPlus* fail to connect, getting a "Received a registry entry that is unknown to this client." message instead.

### Steps to Reproduce

1. Load singleplayer world and open to LAN
2. Have another player/instance try to connect

### Expected Behavior

Client can connect, as both are using the same version of Minecraft.

**Comment by FlorianMichael** [comment]
Thanks for reporting, fixed in latest dev builds at https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/

**Comment by FlorianMichael** [comment]
Please make a new issue and provide your crash log.
