### ISSUE TITLE
The middle mouse button block is kicked

### ISSUE THREAD

**Issue by FandMC** [ViaVersion/ViaFabricPlus#660]
### General Information

[20:38:46] [Render thread/INFO]: Connecting to fandmc.mcbbs.cyou, 25565
[20:38:49] [Render thread/INFO]: New Xaero hud session initialized!
[20:38:49] [Render thread/INFO]: New world map session initialized!
[20:38:49] [Render thread/INFO]: Reloading pipeline on dimension change: minecraft:overworld => minecraft:overworld
[20:38:49] [Render thread/INFO]: Destroying pipeline minecraft:overworld
[20:38:49] [Render thread/INFO]: Creating pipeline for dimension minecraft:overworld
[20:38:49] [Render thread/INFO]: Started 10 worker threads
[20:38:49] [Render thread/WARN]: Unable to find entity: 'minecraft:boat'
[20:38:49] [Render thread/INFO]: Using 3 total BufferAllocator caches
[20:38:49] [Render thread/INFO]: LitematicaSchematic: executing Vanilla DataFixer for Tile Entities DataVersion 2730 -> 4189
[20:39:05] [Render thread/INFO]: LitematicaSchematic: executing Vanilla DataFixer for Entities DataVersion 2730 -> 4189
[20:39:06] [Render thread/INFO]: LitematicaSchematic: executing Vanilla DataFixer for Block State Palette DataVersion 2730 -> 4189
[20:39:06] [Render thread/WARN]: [REI] Found 1 existing reload task(s) after trying to terminate them!
[20:39:06] [Render thread/INFO]: [System] [CHAT] sb20018qswl加入了游戏
[20:39:06] [REI-ReloadPlugins/INFO]: [REI] OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
[20:39:06] [REI-ReloadPlugins/INFO]: [REI] REICommonPlugin starting main-reload for START.
[20:39:06] [REI-ReloadPlugins/INFO]: [REI] Plugins (3):
[20:39:06] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[20:39:06] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[20:39:06] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[20:39:06] [REI-ReloadPlugins/INFO]: [REI] OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
[20:39:06] [Render thread/INFO]: Loaded 3 advancements
[20:39:06] [Render thread/INFO]: [System] [CHAT] [FandMC] 欢迎回来，已帮你自动登录到此服务器
[20:39:06] [Render thread/INFO]: [System] [CHAT] [FandMC] 已成功登录！
[20:39:06] [REI-ReloadPlugins/INFO]: [REI] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[20:39:06] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin starting main-reload for START.
[20:39:06] [REI-ReloadPlugins/INFO]: [REI] Plugins (5):
[20:39:06] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[20:39:06] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[20:39:06] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[20:39:06] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) REITooltipPlugin of REITooltipPlugin [appleskin]
[20:39:06] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) ReiRecipeAction of ReiRecipeAction [wthit]
[20:39:06] [REI-ReloadPlugins/INFO]: [REI] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[20:39:06] [REI-ReloadPlugins/INFO]: [REI] REICommonPlugin finished post-reload for START in 190.1 μs, totaling 2.034 ms.
[20:39:06] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin finished post-reload for START in 303.1 μs, totaling 48.08 ms.
[20:39:06] [REI-ReloadPlugins/INFO]: [REI] ----------------------------------------
[20:39:06] [REI-ReloadPlugins/INFO]: [REI] REICommonPlugin starting main-reload for END.
[20:39:06] [REI-ReloadPlugins/INFO]: [REI] Plugins (3):
[20:39:06] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultPlugin of DefaultPlugin [roughlyenoughitems]
[20:39:06] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) FabricFluidAPISupportPlugin
[20:39:06] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultRuntimePlugin of DefaultRuntimePlugin [roughlyenoughitems]
[20:39:06] [REI-ReloadPlugins/INFO]: [REI] ----------------------------------------
[20:39:06] [REI-ReloadPlugins/ERROR]: [REI] Failed to run end-reload task for reloadable [ServerDisplayRegistryImpl] in stage [END]
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.method_3772()" because the return value of "dev.architectury.utils.GameInstance.getServer()" is null
	at knot/me.shedaniel.rei.impl.common.registry.displays.ServerDisplayRegistryImpl.getAllSortedRecipes(ServerDisplayRegistryImpl.java:230) ~[%5BREI物品管理器%5D%20RoughlyEnoughItems-18.0.796-fabric.jar:?]
	at knot/me.shedaniel.rei.impl.common.registry.displays.ServerDisplayRegistryImpl.fillRecipes(ServerDisplayRegistryImpl.java:216) ~[%5BREI物品管理器%5D%20RoughlyEnoughItems-18.0.796-fabric.jar:?]
	at knot/me.shedaniel.rei.impl.common.registry.displays.ServerDisplayRegistryImpl.endReload(ServerDisplayRegistryImpl.java:209) ~[%5BREI物品管理器%5D%20RoughlyEnoughItems-18.0.796-fabric.jar:?]
	at knot/me.shedaniel.rei.api.common.registry.Reloadable.endReload(Reloadable.java:47) ~[%5BREI物品管理器%5D%20RoughlyEnoughItems-18.0.796-fabric.jar:?]
	at knot/me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.reload(PluginManagerImpl.java:464) ~[%5BREI物品管理器%5D%20RoughlyEnoughItems-18.0.796-fabric.jar:?]
	at knot/me.shedaniel.rei.impl.common.plugins.ReloadManagerImpl.reloadPlugins0(ReloadManagerImpl.java:155) ~[%5BREI物品管理器%5D%20RoughlyEnoughItems-18.0.796-fabric.jar:?]
	at knot/me.shedaniel.rei.impl.common.plugins.ReloadManagerImpl.reloadPlugins0(ReloadManagerImpl.java:144) ~[%5BREI物品管理器%5D%20RoughlyEnoughItems-18.0.796-fabric.jar:?]
	at knot/me.shedaniel.rei.impl.common.plugins.ReloadManagerImpl.lambda$reloadPlugins$7(ReloadManagerImpl.java:122) ~[%5BREI物品管理器%5D%20RoughlyEnoughItems-18.0.796-fabric.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[20:39:06] [REI-ReloadPlugins/INFO]: [REI] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[20:39:06] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin starting main-reload for END.
[20:39:06] [REI-ReloadPlugins/INFO]: [REI] Plugins (5):
[20:39:06] [REI-ReloadPlugins/INFO]: [REI]  - (-100.00) DefaultClientPlugin of DefaultClientPlugin [roughlyenoughitems]
[20:39:06] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) HideIngredientsFromTagsPlugin of HideIngredientsFromTagsPlugin [roughlyenoughitems]
[20:39:06] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) DefaultClientRuntimePlugin of DefaultClientRuntimePlugin [roughlyenoughitems]
[20:39:06] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) REITooltipPlugin of REITooltipPlugin [appleskin]
[20:39:06] [REI-ReloadPlugins/INFO]: [REI]  - (0.00) ReiRecipeAction of ReiRecipeAction [wthit]
[20:39:06] [REI-ReloadPlugins/INFO]: [REI] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[20:39:06] [REI-ReloadPlugins/INFO]: [REI] REICommonPlugin finished post-reload for END in 739.7 μs, totaling 4.129 ms.
[20:39:06] [REI-ReloadPlugins/INFO]: [REI] REIClientPlugin finished post-reload for END in 786.0 μs, totaling 88.29 ms.
[20:39:06] [Render thread/WARN]: encodeClientData(): encountered [4] sendPayload failures, cancelling any Servux join attempt(s)
[20:39:10] [Render thread/INFO]: Xaero hud session finalized.
[20:39:10] [Render thread/INFO]: Finalizing world map session...
[20:39:10] [Thread-14/INFO]: World map cleaned normally!
[20:39:10] [Render thread/INFO]: World map session finalized.
[20:39:10] [Render thread/INFO]: Stopping worker threads
[20:39:10] [Render thread/WARN]: Client disconnected with reason: You were kicked from lobby: Invalid hotbar selection (Hacking?)
minecraft version 1.21.4

### Bug Description

The middle mouse button block on the server has been kicked

### Steps to Reproduce

1. join 1.21.1 server
2. middle mouse button block

### Expected Behavior

I shouldn't have been kicked

**Comment by FandMC** [comment]
![01b4c020-6e38-4650-aa03-18947cd9884c](https://github.com/user-attachments/assets/1b607e39-b8ed-4d25-9ed4-6dfdd1d3d42f)
test server fandmc.mcbbs.cyou

**Comment by FlorianMichael** [comment]
What ViaFabricPlus version do you use?

**Comment by FandMC** [comment]
3.6.1
![f9e4c1cd-6228-46e7-a065-6286691724cd](https://github.com/user-attachments/assets/94d7ebd8-2406-4ae9-9931-8cb42ca1c972)

**Comment by FandMC** [comment]
控制台log
![e2bd3add-db1a-42ff-a496-8bdee53b5313](https://github.com/user-attachments/assets/2a9bf020-b37b-48bd-a78f-433de78c0e64)

**Comment by FandMC** [comment]
I have selected 1.21.1 from the protocol list
This is my mod list
![fa71f154-e422-4672-93d5-e0b2dd99124e](https://github.com/user-attachments/assets/9e2c5fdf-8c8c-4db4-b59d-a
![83e008e7-baec-437e-b3a4-f78ce3b09871](https://github.com/user-attachments/assets/bcd058b5-a905-41c0-a113-61087b29125c)
3e5c9ea1ef2)

**Comment by FandMC** [comment]
Invalid hotbar selection in net.minecraft.server.network.ServerGamePacketListenerImpl 999 and 2174，        if (!(packet.getSlot() >= 0 && packet.getSlot() < this.player.getInventory().items.size())) {
            ServerGamePacketListenerImpl.LOGGER.warn("{} tried to set an invalid carried item", this.player.getName().getString());
            this.disconnect(Component.literal("Invalid hotbar selection (Hacking?)"), org.bukkit.event.player.PlayerKickEvent.Cause.ILLEGAL_ACTION); // Paper - kick event cause
            return;
        }
and  else {
            ServerGamePacketListenerImpl.LOGGER.warn("{} tried to set an invalid carried item", this.player.getName().getString());
            this.disconnect(Component.literal("Invalid hotbar selection (Hacking?)"), org.bukkit.event.player.PlayerKickEvent.Cause.ILLEGAL_ACTION); // CraftBukkit // Paper - kick event cause
        }

**Comment by FlorianMichael** [comment]
Try if this happens with only ViaFabricPlus installed

**Comment by FandMC** [comment]
Still the same, I disabled all mods

**Comment by FandMC** [comment]
![image](https://github.com/user-attachments/assets/fb6a20e9-b257-4d9a-bf3b-db0955fa322d)
![image](https://github.com/user-attachments/assets/83c14d02-50b5-42bf-a5ba-311008923373)

**Comment by FandMC** [comment]
[01:09:05] [Render thread/INFO]: Connecting to 127.0.0.1, 25565
[01:09:06] [Render thread/INFO]: [System] [CHAT] sb20018qswl加入了游戏
[01:09:06] [Render thread/INFO]: Loaded 2 advancements
[01:09:13] [Netty Client IO #5/ERROR]: An exception occurred while handling a packet
java.io.IOException: 你的主机中的软件中止了一个已建立的连接。
	at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:54) ~[?:?]
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:137) ~[?:?]
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:81) ~[?:?]
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:542) ~[?:?]
	at knot/io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:414) ~[netty-transport-4.1.115.Final.jar:?]
	at knot/io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:929) ~[netty-transport-4.1.115.Final.jar:?]
	at knot/io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:359) ~[netty-transport-4.1.115.Final.jar:?]
	at knot/io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:893) ~[netty-transport-4.1.115.Final.jar:?]
	at knot/io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1319) ~[netty-transport-4.1.115.Final.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:935) ~[netty-transport-4.1.115.Final.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:921) ~[netty-transport-4.1.115.Final.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:907) ~[netty-transport-4.1.115.Final.jar:?]
	at knot/io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125) ~[netty-transport-4.1.115.Final.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:939) ~[netty-transport-4.1.115.Final.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:957) ~[netty-transport-4.1.115.Final.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:982) ~[netty-transport-4.1.115.Final.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:950) ~[netty-transport-4.1.115.Final.jar:?]
	at knot/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:1000) ~[netty-transport-4.1.115.Final.jar:?]
	at knot/io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:974) ~[netty-transport-4.1.115.Final.jar:?]
	at knot/io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:305) ~[netty-transport-4.1.115.Final.jar:?]
	at knot/net.minecraft.class_2535.method_36942(class_2535.java:350) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2535.method_52917(class_2535.java:345) ~[client-intermediary.jar:?]
	at knot/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.115.Final.jar:?]
	at knot/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.115.Final.jar:?]
	at knot/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.115.Final.jar:?]
	at knot/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566) ~[netty-transport-4.1.115.Final.jar:?]
	at knot/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.115.Final.jar:?]
	at knot/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.115.Final.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[01:09:14] [Render thread/WARN]: Client disconnected with reason: 连接中断

**Comment by MysticMia** [comment]
I got this same issue with my modlist. I removed all mods and joined with only fabric-api 0.114.2 and ViaFabricPlus 4.0.1.

|  |  |  |  |
|--------|--------|--------|--------|
| 15:44:23.275 | ChunkBuilder | Render thread | Stopping worker threads |
| 15:44:23.278 | net.minecraft.class_8673 | Render thread | Client disconnected with reason: Invalid hotbar selection (Hacking?) |

On the other hand, joining with all my mods except ViaFabricPlus resulted in no kick.
There were no crashes or other errors in the log.

I joined a server with the ip `orcacreative.tk`. Server version 1.21.0, client version 1.21.4

**Comment by Codestian** [comment]
I also have this issue, running Fabric 1.21.4 with only ViaFabricPlus 4.0.1 and Fabric API, tried entering servers below 1.21.1 (on paperMC)

**Comment by Zoriot** [comment]
It's still valid when using VFP 4.0.2 with Fabric 1.21.4 trying to connect to a Paper 1.21.1 server and also with Paper 1.20.1 server. 
I looked into the problem. Maybe it has something to do with [ItemPick1_21_3.java#L109](<https://github.com/ViaVersion/ViaFabricPlus/blob/e321ee4f3753d2c397198184f14fede8bf8c56a4/src/main/java/com/viaversion/viafabricplus/features/world/item_picking/ItemPick1_21_3.java#L109>)? I do not understand where the 36 comes from and how it makes sense. 
Someone else might try removing that + debugging what slot it sends. Because it is definitely sending the wrong slot ID according to [this check](<https://github.com/PaperMC/Paper/blob/edda0db18b0c9b0304e06fb167b218d1e1cf8d55/paper-server/patches/sources/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch#L1360>). I can do that too, but it will take some time. Most likely, I can only do it after the middle of next week.

**Comment by FlorianMichael** [comment]
Fixed in dev builds at https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/;

@Zoriot The + 36 comes from the original game source.

**Comment by Zoriot** [comment]
> Fixed in dev builds at https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/;
> 
> @Zoriot The + 36 comes from the original game source.

Tysm! 
Okay yea I have not looked into it 🙈
