### ISSUE TITLE
Game freeze on specific setup and version of viafabricplus when it loads entity with illegal characters

### ISSUE THREAD

**Issue by Dai-Son** [ViaVersion/ViaFabricPlus#666]
### General Information

[18:35:43] [Render thread/WARN]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[18:35:43] [Render thread/ERROR]: Error executing task on Client
net.minecraft.class_148: Main thread packet handler
	at net.minecraft.class_2600.method_11072(class_2600.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: Invalid entity data item type for field 16 on entity class_1560['(副本)Lv.153 時間神殿-時光使者'/32317, l='ClientLevel', x=-644.52, y=164.06, z=426.54]: old=Optional.empty(class java.util.Optional), new=Optional.empty(class java.util.Optional)
	at net.minecraft.class_2945.method_12785(class_2945.java:204) ~[client-intermediary.jar:?]
	at net.minecraft.class_2945.method_12779(class_2945.java:191) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11093(class_634.java:529) ~[client-intermediary.jar:?]
	at net.minecraft.class_2739.method_11808(class_2739.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_2739.method_11054(class_2739.java:10) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[client-intermediary.jar:?]
	... 18 more
[18:35:43] [Render thread/WARN]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[18:35:43] [Render thread/ERROR]: Error executing task on Client
net.minecraft.class_148: Main thread packet handler
	at net.minecraft.class_2600.method_11072(class_2600.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: Invalid entity data item type for field 16 on entity class_1560['(副本)Lv.153 時間神殿-時光使者'/32317, l='ClientLevel', x=-644.52, y=164.00, z=426.54]: old=Optional.empty(class java.util.Optional), new=Optional.empty(class java.util.Optional)
	at net.minecraft.class_2945.method_12785(class_2945.java:204) ~[client-intermediary.jar:?]
	at net.minecraft.class_2945.method_12779(class_2945.java:191) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11093(class_634.java:529) ~[client-intermediary.jar:?]
	at net.minecraft.class_2739.method_11808(class_2739.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_2739.method_11054(class_2739.java:10) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[client-intermediary.jar:?]
	... 18 more

### Bug Description

Use 1.20.4 (Viafabricplus >= 3.1.1, <=3.1.0 everything works fine) with 1.11.1-1.11.2 loads entity with illegal characters
game freeze
**The problem is it didnt happen in every setup**
have friend have same mods and same java version and config it won't freeze, also same modpack in my VM didnt freeze when load

### Steps to Reproduce

1. join server play.qpond.net
2. loads map with entity with illegal characters
3. game freeze every 1-2seconds with random period

### Expected Behavior

should be run smoothly

**Comment by FlorianMichael** [comment]
Can't reproduce, please make sure this happens without any other mods installed and if so provide more detailed steps on how to reproduce the issue.
